name: "🐞 Bug Report / Fehlerbericht"
description: "Report a bug in English or German. This template will automatically apply the 'bug' label."
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Disclaimer / Hinweis:**  
        Bugs can be reported in **English or German**. Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: input
    id: description
    attributes:
      label: "Description / Beschreibung"
      description: "Describe the bug briefly and clearly / Beschreiben Sie den Fehler kurz und klar"
      placeholder: "A clear and concise description of what the bug is / Eine klare und präzise Beschreibung des Fehlers"
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs / Protokolle"
      description: "Paste any relevant logs here **inside the code fences**. Do not remove the triple backticks. / Fügen Sie relevante Protokolle hier ein **innerhalb der Codeblöcke** ein. Entfernen Sie die ``` nicht."
      default: "```\nPaste your logs here\n```"
      placeholder: "```\nYour logs here\n```"
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce / Schritte zum Reproduzieren (optional)"
      description: "Step-by-step instructions to reproduce the behavior / Schritt-für-Schritt-Anleitung, um das Verhalten zu reproduzieren"
      placeholder: "1. ...\n2. ...\n3. ..."
      required: false

  - type: input
    id: version
    attributes:
      label: "Version used / Verwendete Version"
      description: "Please provide the version in the format x.y.z-alpha|beta / Bitte geben Sie die Version im Format x.y.z-alpha|beta an"
      placeholder: "0.0.1-alpha1"
      required: true

  - type: input
    id: os
    attributes:
      label: "Operating System / Betriebssystem"
      description: "Which OS was used / Welches Betriebssystem wurde verwendet"
      placeholder: "Windows 11, Ubuntu 22.04, macOS 14, etc."
      required: true