name: "💡 Feature Request / Funktionswunsch"
description: "Suggest a new feature or improvement. This template can be used in English or German."
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        **Disclaimer / Hinweis:**  
        Feature requests can be submitted in **English or German**. Please provide as much detail as possible to help us understand your suggestion.

  - type: textarea
    id: description
    attributes:
      label: "Description / Beschreibung"
      description: "Describe the feature or improvement in detail / Beschreiben Sie die Funktion oder Verbesserung im Detail"
      placeholder: "Explain what the feature should do and why it is useful / Erklären Sie, was die Funktion tun soll und warum sie nützlich ist"
      required: true
