name: "📝 General Feedback / Allgemeines Feedback"
description: "Share your thoughts on the game, the look and feel, or general impressions. This template can be used in English or German."
title: "[FEEDBACK] "
labels: ["feedback"]
body:
  - type: markdown
    attributes:
      value: |
        **Disclaimer / Hinweis:**  
        General feedback can be submitted in **English or German**. This is for thoughts, impressions, or suggestions that are neither bugs nor specific feature requests.

  - type: textarea
    id: feedback
    attributes:
      label: "Feedback / Rückmeldung"
      description: "Please describe your feedback clearly / Bitte beschreiben Sie Ihr Feedback klar und deutlich"
      placeholder: "I like the UI design, but the color palette could be a bit warmer. / Mir gefällt das UI-Design, aber die Farbpalette könnte etwas wärmer sein."
      required: true

  - type: input
    id: context
    attributes:
      label: "Context / Kontext (optional)"
      description: "If relevant, indicate what part of the game or app this feedback applies to / Falls relevant, geben Sie an, auf welchen Teil des Spiels oder der App sich das Feedback bezieht"
      placeholder: "Main menu, gameplay, tutorial, etc. / Hauptmenü, Spielablauf, Tutorial usw."
      required: false
